### ISSUE TITLE
dependence error when I add this package

### ISSUE THREAD

**Issue by feilongfl** [renancaraujo/photo_view#94]
I got an error when  I add this package to my project.I'm a newbie in flutter,I have no idea how can I solve it.

```
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because bilibrowser depends on photo_view >=0.2.0 which requires SDK version >=2.1.0 <3.0.0, version solving failed.
Unable to reload your application because "flutter packages get" failed to update package dependencies.
Exception: pub get failed (1)
```

pubspec.yaml
```
name: bilibrowser
description: A bilibili browser.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  url_launcher: ^5.0.0
  cached_network_image: ^0.5.1
  html: ^0.13.3
  #  chewie: ^0.9.5
  chewie:
    git:
      url: git://github.com/feilongfl/chewie.git
  screen: ^0.0.4
  loadmore: ^1.0.3
#  photo_view: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^1.0.0
  path: ^1.5.1
  test: ^1.3.3


flutter:
  uses-material-design: true

  assets:
  #  - res/images/loading.gif
  - res/images/Placeholder.png
  - res/images/LoginLogo.png
  - res/images/launch_image.jpg

targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generate_to_json_function: true
          include_if_null: true
          nullable: true
          use_wrappers: false
```
